"""Builds the Supplementary Material (LaTeX) directly from the result tables of the repository."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs"


def esc(x) -> str:
    s = str(x)
    for a, b in [("\\", r"\textbackslash{}"), ("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#")]:
        s = s.replace(a, b)
    return s


def num(v: float) -> str:
    if v.is_integer():
        return f"{v:,.0f}"
    if abs(v) < 0.1:
        return f"{v:.4g}"
    return f"{v:,.2f}"


def table(df: pd.DataFrame, caption: str, label: str, fmt: dict | None = None) -> str:
    fmt = fmt or {}
    cols = list(df.columns)
    spec = "l" + "r" * (len(cols) - 1)
    lines = [r"\begin{table}[H]", r"\centering", r"\scriptsize", rf"\caption{{{caption}}}", rf"\label{{{label}}}",
             r"\begin{adjustbox}{max width=\linewidth}", rf"\begin{{tabular}}{{{spec}}}", r"\hline",
             " & ".join(esc(c) for c in cols) + r" \\", r"\hline"]
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            if pd.isna(v):
                cells.append("--")
            elif c in fmt:
                cells.append(fmt[c].format(v))
            elif isinstance(v, float):
                cells.append(num(v))
            else:
                cells.append(esc(v))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{adjustbox}", r"\end{table}", ""]
    return "\n".join(lines)


def read(path: str) -> pd.DataFrame:
    return pd.read_csv(OUT / path, encoding="utf-8-sig")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    parts = [r"""\documentclass[11pt]{article}
\usepackage[a4paper,margin=2cm]{geometry}
\usepackage{booktabs,adjustbox,url,float}
\def\UrlBreaks{\do\/\do-\do_\do.\do=}
\setlength{\emergencystretch}{3em}
\renewcommand{\thetable}{S\arabic{table}}
\begin{document}
\begin{center}{\large\bfseries Supplementary Material}\\[4pt]
Assessing Context-Conditioned Soybean Sowing Date and Supplemental Irrigation Decisions Using DSSAT and Reinforcement Learning\end{center}

All tables are generated by \path{src/build_supplement.py} from files in the folder \path{dssat_rl_soybean/outputs} of the repository \url{https://github.com/GabyQueiroz/RLDSSAT_Soybean}; the source file of each table is given in its caption.
"""]

    # S1 configurations
    parts.append(r"\section*{S1. Configurations}")
    rows = []
    for name, path in [("Experiment 1 (INMET)", "configs/experiment_castro_t0.yaml"), ("Experiment 2 (NASA POWER)", "configs/experiment_castro_power.yaml")]:
        c = yaml.safe_load((ROOT / path).read_text(encoding="utf-8"))
        ag, p = c["agronomy"], c["ppo"]
        rows.append({"Item": "Configuration file", name: path})
        for k, v in [("Decision date", c["decision"]["decision_month_day"]), ("Context mode", c["decision"]["context_mode"]),
                     ("Sowing window", f"{ag['planting_window_start']} to {ag['planting_window_end']}"),
                     ("Trigger range (mm)", str(ag["trigger_range_mm"])), ("Max depth per event (mm)", ag["max_single_irrigation_mm"]),
                     ("Minimum event (mm)", ag["min_irrigation_event_mm"]), ("Inspection interval (d)", ag["irrigation_check_days"]),
                     ("Spin-up start", c["simulation"]["spinup_start_month_day"]), ("Weather end", c["simulation"]["weather_end_month_day"]),
                     ("Y_ref (kg/ha)", c["reward"]["target_yield_kg_ha"]), ("kappa (1/mm)", c["reward"]["water_penalty_per_mm"]),
                     ("Network", str(p["net_arch"])), ("Context noise", p["context_noise_std"]), ("Learning rate", p["learning_rate"]),
                     ("Clip range", p["clip_range"]), ("Environments x steps", f"{p['n_envs']} x {p['n_steps']}"), ("Batch size", p["batch_size"]),
                     ("Epochs", p["n_epochs"]), ("Min / max steps", f"{p['min_timesteps']} / {p['total_timesteps']}"),
                     ("Evaluation interval", p["eval_freq"]), ("Patience (evaluations)", p["patience_evals"])]:
            rows.append({"Item": k, name: str(v)})
    cfg_tab = pd.DataFrame(rows).groupby("Item", sort=False).first().reset_index()
    parts.append(table(cfg_tab, "Main settings of the two experiments (configs/experiment\\_castro\\_t0.yaml and configs/experiment\\_castro\\_power.yaml).", "tab:s_config"))
    parts.append(r"The registry of the rolling-origin evaluation, with its two amendments, is \path{configs/ROLLING_ORIGIN_REGISTRY.md}; the configuration of every run is in \path{configs/_generated_rolling_power}, \path{configs/_generated_rolling_power_k0}, \path{configs/_generated_rolling_power_k6} and \path{configs/_generated_ppo_castro_t0}.")

    # S2 soil
    parts.append(r"\section*{S2. Soil profile}")
    soil = read("ppo_soja_castro_dssat/tables/synthetic_soil_profile_s2.csv")[["layer_top_cm", "layer_bottom_cm", "slll", "sdul", "ssat", "sbdm", "sloc", "slcl", "slsi", "srgf", "available_water_mm"]]
    parts.append(table(soil, "Synthetic clayey profile used by DSSAT (ppo\\_soja\\_castro\\_dssat/tables/synthetic\\_soil\\_profile\\_s2.csv). It is not a surveyed Castro profile.", "tab:s_soil",
                       {"layer_top_cm": "{:.0f}", "layer_bottom_cm": "{:.0f}", "slcl": "{:.0f}", "slsi": "{:.0f}", "available_water_mm": "{:.0f}"}))

    # S3 weather
    parts.append(r"\section*{S3. Weather data, quality control and planting window}")
    comp = read("ppo_soja_castro_dssat/tables/weather_completeness_by_season.csv")[["season_year", "raw_days", "rain_invalid_days", "temp_invalid_days", "srad_invalid_days", "rain_mm", "temp_mean_c", "split"]]
    parts.append(table(comp, "INMET A819: invalid days (fewer than 18 valid hours for rainfall or temperature, fewer than 6 for radiation) in the September--April window of each season, and the resulting seasonal rainfall and mean temperature after imputation (ppo\\_soja\\_castro\\_dssat/tables/weather\\_completeness\\_by\\_season.csv). The split column refers to the earlier diagnostic configuration.", "tab:s_complete",
                       {"season_year": "{:.0f}", "raw_days": "{:.0f}", "rain_invalid_days": "{:.0f}", "temp_invalid_days": "{:.0f}", "srad_invalid_days": "{:.0f}", "rain_mm": "{:.0f}", "temp_mean_c": "{:.2f}"}))
    parts.append(table(read("supplementary_analyses/tables/qc_threshold_sensitivity.csv"),
                       "Sensitivity of INMET September--April rainfall, mean temperature, radiation and the 30-day pre-season temperature of the context to the daily completeness thresholds, relative to 18 valid hours for rainfall and temperature and 6 for radiation (supplementary\\_analyses/tables/qc\\_threshold\\_sensitivity.csv).", "tab:s_qc",
                       {"min_hours_rain_temp": "{:.0f}", "min_hours_srad": "{:.0f}"}))
    parts.append(table(read("ppo_soja_castro_dssat/tables/weather_imputation_sensitivity_summary.csv"),
                       "Sensitivity of INMET seasonal rainfall to the precipitation-imputation strategy, relative to day-of-year climatology (ppo\\_soja\\_castro\\_dssat/tables/weather\\_imputation\\_sensitivity\\_summary.csv; splits of the earlier diagnostic configuration). Zero filling is a dry lower bound.", "tab:s_imput",
                       {"seasons": "{:.0f}"}))
    parts.append(table(read("power_station_agreement/tables/power_vs_station_daily.csv"),
                       "Agreement between INMET A819 and NASA POWER on days with valid station data; difference = station minus POWER (power\\_station\\_agreement/tables/power\\_vs\\_station\\_daily.csv).", "tab:s_agree", {"n": "{:,.0f}"}))
    sr = read("power_station_agreement/tables/power_vs_station_season_rain.csv")
    parts.append(table(sr, "September--April rainfall of INMET A819 and NASA POWER by season, with the share of valid station rainfall days (power\\_station\\_agreement/tables/power\\_vs\\_station\\_season\\_rain.csv).", "tab:s_seasonrain",
                       {"season": "{:.0f}", "days": "{:.0f}", "valid_rain_day_share": "{:.2f}", "rain_station_mm": "{:.0f}", "rain_power_mm": "{:.0f}"}))
    parts.append(table(read("ppo_soja_castro_dssat/tables/season_sidra_pairing_audit.csv")[["season_year", "yield_same_sowing_year_kg_ha", "yield_harvest_year_kg_ha", "has_boundary_issue"]],
                       "Season--SIDRA pairing audit: municipal yield of the sowing year and of the harvest year (ppo\\_soja\\_castro\\_dssat/tables/season\\_sidra\\_pairing\\_audit.csv). The harvest-year pairing follows the IBGE PAM rule.", "tab:s_sidra",
                       {"season_year": "{:.0f}", "yield_same_sowing_year_kg_ha": "{:,.0f}", "yield_harvest_year_kg_ha": "{:,.0f}"}))
    z = read("ppo_soja_castro_dssat/tables/zarc_portaria_audit.csv").T.reset_index()
    z.columns = ["Field", "Value"]
    parts.append(table(z, "Audit of the MAPA ZARC ordinance for soybean in Paran\\'a, safra 2024/2025 (ppo\\_soja\\_castro\\_dssat/tables/zarc\\_portaria\\_audit.csv).", "tab:s_zarc"))

    # S4 previous correction
    parts.append(r"\section*{S4. Statistical yield correction of the previous diagnostic configuration}")
    parts.append(table(read("ppo_soja_castro_dssat/tables/yield_correction_alpha_ablation_s4.csv").drop(columns=["source_file"]),
                       "Regularization ablation of the ridge correction used only in the previous diagnostic configuration and removed from the objective (ppo\\_soja\\_castro\\_dssat/tables/yield\\_correction\\_alpha\\_ablation\\_s4.csv).", "tab:s_ridge"))

    # S5 learning
    parts.append(r"\section*{S5. Training runs and selected checkpoints}")
    parts.append(table(read("article_castro_t0/tables/selected_checkpoints.csv"), "Experiment 1: selected checkpoints of seeds 42--46 (article\\_castro\\_t0/tables/selected\\_checkpoints.csv).", "tab:s_ck1",
                       {"seed": "{:.0f}", "selected_timesteps": "{:,.0f}", "stop_timesteps": "{:,.0f}", "n_validation_evaluations": "{:.0f}", "simulation_requests": "{:,.0f}"}))
    ck = read("article_rolling_power/tables/selected_checkpoints.csv").drop(columns=["train", "valid"])
    parts.append(table(ck, "Experiment 2: selected checkpoint of each fold and seed (article\\_rolling\\_power/tables/selected\\_checkpoints.csv). Validation values are means over the five validation seasons of the fold.", "tab:s_ck2",
                       {"seed": "{:.0f}", "n_train": "{:.0f}", "selected_timesteps": "{:,.0f}", "stop_timesteps": "{:,.0f}", "n_evaluations": "{:.0f}"}))
    parts.append(r"Validation curves of every run: \path{tables/validation_curve.csv} in each run folder; TensorBoard logs: \path{tensorboard/} in each run folder.")

    # S6 grid
    parts.append(r"\section*{S6. Candidate grid}")
    parts.append(r"The grid contains 602 rules: 13 sowing offsets (0, 8, \dots, 88, 96 days after September 15) combined with rainfed management or with 45 irrigation rules (trigger 30, 60, 90, 120 or 150 mm; depth 15, 25 or 35 mm; cap 80, 160 or 240 mm), plus four constructed schedules. Simulated yield, irrigation and objective are in \path{final_comparators_castro_t0/tables/candidate_grid_development.csv} and \path{candidate_grid_test.csv} (Experiment 1, 9,030 and 2,408 simulations) and \path{rolling_power_analysis/tables/candidate_grid_all_seasons.csv} (Experiment 2, 24,682 simulations).")
    land = read("article_rolling_power/tables/response_landscape_all_seasons.csv")
    parts.append(table(land, "Experiment 2: raw DSSAT response by season (article\\_rolling\\_power/tables/response\\_landscape\\_all\\_seasons.csv).", "tab:s_land",
                       {c: "{:,.0f}" for c in land.columns}))

    # S7 actions and effects
    parts.append(r"\section*{S7. Actions, paired effects and productivity--water analysis}")
    sl = read("rolling_power_analysis/tables/season_level.csv")
    piv = sl.pivot(index="year", columns="comparator", values="yield_kg_ha")[["PPO", "optimized_fixed_rule", "contextual_knn", "rainfed_oct15", "retrospective_oracle"]].reset_index()
    parts.append(table(piv, "Experiment 2: yield (kg ha$^{-1}$) by test season; PPO is the mean over seeds 42--46 (rolling\\_power\\_analysis/tables/season\\_level.csv).", "tab:s_seasonyield",
                       {c: "{:,.0f}" for c in piv.columns}))
    irr = sl.pivot(index="year", columns="comparator", values="irrigation_mm")[["PPO", "optimized_fixed_rule", "contextual_knn", "retrospective_oracle"]].reset_index()
    parts.append(table(irr, "Experiment 2: seasonal irrigation (mm) by test season (rolling\\_power\\_analysis/tables/season\\_level.csv).", "tab:s_seasonirr", {"year": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/ppo_actions_by_season.csv"), "Experiment 2: PPO actions by test season, mean and standard deviation over seeds (article\\_rolling\\_power/tables/ppo\\_actions\\_by\\_season.csv).", "tab:s_actions", {"year": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/paired_effects_3_vs_5_seeds.csv")[["seeds", "comparator", "mean_d_reward", "mean_d_yield", "ci95_d_yield_low", "ci95_d_yield_high", "seasons_ppo_better_reward", "sd_seed_d_yield"]],
                       "Experiment 2: paired effects with seeds 42--44 (before amendment 2) and seeds 42--46 (article\\_rolling\\_power/tables/paired\\_effects\\_3\\_vs\\_5\\_seeds.csv).", "tab:s_seeds",
                       {"seasons_ppo_better_reward": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/water_frontier_by_kappa.csv"), "Experiment 2: productivity--water results by water penalty (article\\_rolling\\_power/tables/water\\_frontier\\_by\\_kappa.csv).", "tab:s_kappa", {"n": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/yield_regret_common_budget.csv"), "Experiment 2: yield regret under a common seasonal water budget (article\\_rolling\\_power/tables/yield\\_regret\\_common\\_budget.csv).", "tab:s_regret",
                       {"budget_mm": "{:.0f}", "pairs_within_budget": "{:.0f}", "pairs_total": "{:.0f}"}))
    parts.append(table(read("supplementary_analyses/tables/inspection_interval_sensitivity.csv"), "Optimized fixed rule (rolling-origin selection, 20 test seasons) by inspection interval of the irrigation rule; sowing offsets 24, 32 and 40 days (supplementary\\_analyses/tables/inspection\\_interval\\_sensitivity.csv).", "tab:s_interval", {"check_days": "{:.0f}"}))

    # S8 context and diagnostics
    parts.append(r"\section*{S8. Context analysis and simulation diagnostics}")
    parts.append(table(read("article_castro_t0/tables/context_skill_development.csv"), "Experiment 1: Spearman correlation between context variables and season outcomes over the 15 INMET development seasons (article\\_castro\\_t0/tables/context\\_skill\\_development.csv).", "tab:s_skill1", {"n_seasons": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/context_skill_power.csv"), "Experiment 2: Spearman correlation between context variables and season outcomes over the 41 NASA POWER seasons (article\\_rolling\\_power/tables/context\\_skill\\_power.csv).", "tab:s_skill2", {"n_seasons": "{:.0f}"}))
    parts.append(table(read("article_castro_t0/tables/context_position_vs_training.csv"), "Experiment 1: standardized context of each season and its position relative to the training seasons (article\\_castro\\_t0/tables/context\\_position\\_vs\\_training.csv).", "tab:s_pos",
                       {"year": "{:.0f}", "n_features_outside_training_range": "{:.0f}"}))
    parts.append(table(read("article_rolling_power/tables/context_action_correlation.csv"), "Experiment 2: Spearman correlation between the standardized test context and the PPO action (article\\_rolling\\_power/tables/context\\_action\\_correlation.csv).", "tab:s_ctxact"))
    parts.append(table(read("article_rolling_power/tables/action_bound_saturation.csv").T.reset_index().rename(columns={"index": "Indicator", 0: "Share"}), "Experiment 2: share of the 100 season--seed PPO actions at each bound of the action space (article\\_rolling\\_power/tables/action\\_bound\\_saturation.csv).", "tab:s_sat"))
    parts.append(table(read("article_rolling_power/tables/value_of_information_ladder.csv"), "Experiment 2: value-of-information ladder over the 20 test seasons (article\\_rolling\\_power/tables/value\\_of\\_information\\_ladder.csv).", "tab:s_voi"))
    parts.append(table(read("supplementary_analyses/tables/proxy_vs_dssat_summary.csv"), "Proxy water balance of the irrigation rule versus the DSSAT soil-water deficit (198 mm minus extractable soil water), rainfed sowing on October 15, 41 NASA POWER seasons (supplementary\\_analyses/tables/proxy\\_vs\\_dssat\\_summary.csv).", "tab:s_proxy", {"days": "{:,.0f}"}))
    parts.append(table(read("supplementary_analyses/tables/proxy_bins_dssat_deficit.csv"), "DSSAT soil-water deficit (mm) by class of the proxy deficit (supplementary\\_analyses/tables/proxy\\_bins\\_dssat\\_deficit.csv). Negative values indicate soil water above the drained upper limit.", "tab:s_proxybins", {"count": "{:,.0f}"}))
    parts.append(table(read("supplementary_analyses/tables/proxy_vs_et0_summary.csv"), "Daily evaporative demand of the proxy versus FAO-56 Hargreaves reference evapotranspiration, NASA POWER, September--April 1984--2024 (supplementary\\_analyses/tables/proxy\\_vs\\_et0\\_summary.csv).", "tab:s_et0", {"days": "{:,.0f}"}))
    parts.append(table(read("supplementary_analyses/tables/spinup_effect_summary.csv").T.reset_index().rename(columns={"index": "Indicator", 0: "Value"}), "Effect of the August soil-water spin-up on rainfed DSSAT yield and on the ranking of the 13 sowing offsets, 41 NASA POWER seasons (supplementary\\_analyses/tables/spinup\\_effect\\_summary.csv).", "tab:s_spinup"))

    parts.append(r"\end{document}")
    Path(args.output).write_text("\n".join(parts), encoding="utf-8")
    print("written", args.output)


if __name__ == "__main__":
    main()
